# Generated by Django 5.1.4 on 2024-12-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='title',
            name='api_title_year_pu_8e4881_idx',
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='subject',
            field=models.CharField(default='Non catégorisé', max_length=100),
        ),
    ]
